testname: 通道切换&音量测试
testId: volume2
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages: 
    - type: volume2
      id: page1
      name: " "
      content: " "
      stimulus: configs/resources/audio/Tom.wav
      defaultVolume: 1.0
    - type: volume2
      id: page2
      name: " "
      content: " "
      stimulus: configs/resources/audio/man.wav
      defaultVolume: 1.0