testname: webMUSHRA Example
testId: training_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: volume2
      id: page2
      name: Output Channel Selector
      content: This pages present Output Channel Selector.
      stimulus: configs/resources/audio/man2.wav
      defaultVolume: 1.0
    - type: mushra
      id: training_1
      name: Training No.1
      content: This MUSHRA page does not randomize the conditions. Furthermore, the conditions names are not hidden. 
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/man.wav
      randomize: false
      showConditionNames: true
      defaultVolume1: 1.0
      defaultVolume2: 0.1
      defaultVolume3: 1.0
      defaultVolume4: 1.0
      stimuli:
          ch1: configs/resources/audio/man.wav
          ch2: configs/resources/audio/man.wav
          ch3: configs/resources/audio/man.wav   
          ch4: configs/resources/audio/man.wav  

    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other