testname: webMUSHRA Example
testId: training_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: volume2
      id: page2
      name: Output Channel Selector
      content: This pages present Output Channel Selector.
      stimulus: configs/resources/audio/man2.wav
      defaultVolume: 1.0
